---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:

inputs:
  - name: customer-repo
  - name: om-cli

run:
  path: customer-repo/tasks/post-step/task.sh
